apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-retrieval-cronjob
spec:
  schedule: "30 1 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: data-retrieval
        spec:
          containers:
            - name: data-retrieval
              image: {{ ECR_REPOSITORY_URL }}:{{ TAG }}
              env:
                  - name: GITHUB_TOKEN
                    valueFrom:
                      secretKeyRef:
                        name: github
                        key: token
                  - name: PAPERCLIFF_CORE_URL
                    valueFrom:
                      secretKeyRef:
                        name: papercliff-core
                        key: url
                  - name: PAPERCLIFF_CORE_HEADER_NAME
                    valueFrom:
                      secretKeyRef:
                        name: rapidapi
                        key: proxy-header
                  - name: PAPERCLIFF_CORE_HEADER_VALUE
                    valueFrom:
                      secretKeyRef:
                        name: rapidapi
                        key: proxy-secret
              args:
                - lein
                - run
                - -m
                - data-retrieval.core
          restartPolicy: OnFailure
